### PR TITLE
Display year, seconds, tz when creating tokens

### LINKED ISSUE #260: Flowauth should display year (and also seconds and timezone?) in the token expiry date
**Describe the bug**
Flowauth does not display the year in the token expiry date, making it impossible to know when exactly a token will expire. Similarly, it would be helpful if it displayed token expiry up to second resolution, and also displayed the timezone (or made it clear that it refers to UTC if that's the case?)

**Product**
Flowauth

**Version**
Latest master (e03de7b0f0a3d)

**To Reproduce**

1. Follow the steps in #259 until step 6.
2. Notice that the token expiry date reads "January 1st 12:00 am".

**Expected behavior**

The token expiry date should read "1st January 2019, 12:00 am" or similar.

In fact, I'd prefer if the information was as comprehensive as possible so I'd like to see second-resolution and timezone information as well.

**Screenshots**

screen shot 2019-01-19 at 11 07 05

### PR DESCRIPTION
**Pull request by greenape**
Closes #260

### I have:

- [ ] Formatted any Python files with [black](https://github.com/ambv/black)
- [x] Brought the branch up to date with master
- [x] Added any relevant Github labels
- [ ] Added tests for any new additions
- [ ] Added or updated any relevant documentation
- [ ] Added an Architectural Decision Record (ADR), if appropriate
- [ ] Added an [MPLv2 License Header](https://www.mozilla.org/en-US/MPL/headers/) if appropriate
- [x] Updated the [Changelog](https://github.com/Flowminder/FlowKit/blob/master/CHANGELOG.md) 

### Description

Switches the display of token expiry date time in the create token screen from:

Screenshot 2019-06-04 at 16 12 26

to:

Screenshot 2019-06-04 at 16 12 11

### CODE REVIEW

File: flowauth/frontend/src/TokenDetails.js [hunk 1]
```diff
@@ -201,16 +212,22 @@ class TokenDetails extends React.Component {
...
           <MuiPickersUtilsProvider utils={DateFnsUtils}>
             <DateTimePicker
               value={expiry}
               onChange={this.handleDateChange}
               disablePast={true}
               maxDate={latest_expiry}
+              format="yyyy/MM/dd HH:mm:ss"
+              ampm={false}
+              margin="normal"
+              helperText={new Date().toTimeString().slice(9)}
```
Comment (maxalbert) [inline flowauth/frontend/src/TokenDetails.js]: Can we add a comment here that says this displays the timezone (which is not obvious otherwise)?
