### PR TITLE
Fix adding api routes to servers

### LINKED ISSUE #1373: Can't add new API permissions to an existing server in FlowAuth
**Describe the bug**
If I log into FlowAuth as an admin user, and add a new API route, the new API permissions appear greyed-out in the 'Edit Server' view for an existing server, and can't be selected.

**To Reproduce**
1. Spin up FlowAuth in demo mode, and log in as 'TEST_ADMIN'.
2. In the 'API Routes' tab, add a new capability 'available_dates'.
3. Select the 'Servers' tab, and edit 'TEST_SERVER'.
4. Expand the 'API Permissions' block.
4. The 'available_dates' heading is visible, but the tick-boxes are greyed-out.

**Expected behavior**
When a new API route is added through the FlowAuth UI, it should then be possible to add this as an API permission for an existing server.

### PR DESCRIPTION
**Pull request by greenape**
Closes #1373

### I have:

- [ ] Formatted any Python files with [black](https://github.com/ambv/black)
- [x] Brought the branch up to date with master
- [x] Added any relevant Github labels
- [x] Added tests for any new additions
- [ ] Added or updated any relevant documentation
- [ ] Added an Architectural Decision Record (ADR), if appropriate
- [x] Added an [MPLv2 License Header](https://www.mozilla.org/en-US/MPL/headers/) if appropriate
- [x] Updated the [Changelog](https://github.com/Flowminder/FlowKit/blob/master/CHANGELOG.md) 

### Description

Fixes not being able to turn on a newly added api route for an existing server by correctly setting the permitted options on servers to all options, and adds a test to cover this case.

### CODE REVIEW

File: flowauth/frontend/cypress/integration/add_new_route.js [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+    cy.get("#name").should("be.empty");
+    cy.contains(route_name).should("exist");
+    cy.get("#server_list")
+      .click()
+      .get("#edit_1")
+      .click()
+      .get("#api-exp")
+      .click();
+    cy.get("#permissions").should("have.attr", "data-indeterminate", "true");
+    cy.get("[data-permission-id='" + route_name + "_get_result']")
```
Comment (maxalbert) [inline flowauth/frontend/cypress/integration/add_new_route.js]: Worth creating a helper function for this check (with a meaningful name) to avoid the code repetition?

File: flowauth/frontend/cypress/integration/add_new_route.js [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+      .should("not.be.disabled");
+    cy.get("#api_routes").click();
+    cy.contains(route_name)
+      .parent()
+      .parent()
+      .find("button")
+      .click({
+        force: true
+      });
+    cy.contains(route_name).should("not.exist");
```
Comment (maxalbert) [inline flowauth/frontend/cypress/integration/add_new_route.js]: Just for my clarification: what does this check do, exactly? Why should the `route_name` element not exist any more?

File: flowauth/frontend/src/PermissionDetails.jsx [hunk 3]
```diff
@@ -206,7 +214,7 @@ class PermissionDetails extends React.Component {
       isPermissionChecked,
       permissionIndeterminate
     } = this.state;
-    const { classes, onClick, permitted } = this.props;
```
Comment (maxalbert) [inline flowauth/frontend/src/PermissionDetails.jsx]: Out of interest: was the presence of `onClick` a bug, or did you have to remove it because of any changes in this PR?

File: flowauth/frontend/cypress/integration/add_new_route.js (hunk 2 above)
Comment (greenape) [reply flowauth/frontend/cypress/integration/add_new_route.js]: This is a convoluted way to click the dustbin icon next to it, which should delete it.

File: flowauth/frontend/src/PermissionDetails.jsx (hunk 3 above)
Comment (greenape) [reply flowauth/frontend/src/PermissionDetails.jsx]: Not a bug, just an unused var.
