### PR TITLE
Fix delete from list

### LINKED ISSUE #163: Deleting groups is broken in FlowAuth
**Describe the bug**
Groups, users, servers etc. can't be deleted.

**Product**
FlowAuth

**Version**
master

**Additional context**

Issue is in `Listing.js`, L36 - `deleteAction.` should read `deleteAction(obj_id).`

### PR DESCRIPTION
**Pull request by greenape**
Closes #163

### I have:

- [ ] Formatted any Python files with [black](https://github.com/ambv/black)
- [x] Brought the branch up to date with master
- [x] Added any relevant Github labels
- [x] Added tests for any new additions
- [ ] Added or updated any relevant documentation
- [ ] Added an Architectural Decision Record (ADR), if appropriate
- [ ] Added an [MPLv2 License Header](https://www.mozilla.org/en-US/MPL/headers/) if appropriate 

### Description

Fixes not being able to delete users/groups/servers, and adds some tests that cover groups admin

### CODE REVIEW

File: flowauth/frontend/cypress/integration/group_list.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+    beforeEach(function() {
+        // Log in and navigate to user details screen
+        cy.login_admin();
+        cy.visit("/");
+        cy.get("#group_admin").click();
+    });
+
+    it("Add group", function() {
+        // Add a new group
```
Comment (maxalbert) [inline flowauth/frontend/cypress/integration/group_list.js]:
```suggestion
        // Add a new group
        cy.contains("DUMMY_GROUP").should('not.exist')
```

File: flowauth/frontend/cypress/integration/group_list.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+        cy.get("#new").click();
+        cy.get("#group_name").type("DUMMY_GROUP");
+        cy.contains("Save").click();
+        // Check that new group appears
+        cy.contains("DUMMY_GROUP").should("be.visible");
+    });
+
+    it("Delete group", function() {
+        cy.get("#rm_2").click();
```
Comment (maxalbert) [inline flowauth/frontend/cypress/integration/group_list.js]:
```suggestion
        cy.contains("Test Group").should("be.visible");
        cy.get("#rm_2").click();
```
