### PR TITLE
FlowAuth login error messages

### LINKED ISSUE #76: FlowAuth login error messages
Subcategory of #54.

The FlowAuth login screen should display an error message if your login credentials are incorrect, or something unexpected happened behind the scenes.

As a corollary, a helpful error message should be sent back from the backend if credentials are bad (currently sends a 401, should still send a 401 but with a json package as we do for the 400 errors).

### PR DESCRIPTION
**Pull request by jch1g10**
Closes #76

### I have:

- [x] Formatted any Python files with [black](https://github.com/ambv/black)
- [x] Brought the branch up to date with master
- [x] Added any relevant Github labels
- [x] Added tests for any new additions
- [ ] Added or updated any relevant documentation
- [ ] Added an Architectural Decision Record (ADR), if appropriate
- [x] Added an [MPLv2 License Header](https://www.mozilla.org/en-US/MPL/headers/) if appropriate 

### Description

- Define a dialog for displaying errors in the FlowAuth frontend
- Display error dialog on login screen
- Send helpful error messages back from the backend if credentials are bad
- Add tests for login error dialog

@greenape

### CODE REVIEW

File: flowauth/frontend/cypress/integration/login_spec.js [hunk 1]
```diff
@@ -9,3 +13,59 @@ describe("Login", function() {
...
+		cy.get("#password").type("WRONG_PASSWORD");
+		cy.get("button").click();
+		// Check that dialog appears with correct title and description
+		cy.get("#error-dialog-title").should("contain", "Error");
+		cy.get("#error-dialog-description").should("contain", "Incorrect username or password.");
+	});
+});
+
+describe("Login_error_twice", function () {
+	it("Error dialog appears more than once", function () {
```
Comment (maxalbert) [inline flowauth/frontend/cypress/integration/login_spec.js]: Very minor note, but I had to read comments inside the tests to understand what the description meant. How about rephrasing it along the following lines?
```suggestion
	it("Error dialog re-appears after closing if password wasn't changed", function () {
```
